### PR TITLE
Fixed watermarkless extraction

### PR DESCRIPTION
**Pull request by Zipdox**

### CODE REVIEW

**Comment by merqwury** [comment]
Any chance we can merge this in?

**Comment by Eryofus** [comment]
Sadly the fix only works when downloading individual videos. When using "user", "trend", and other commands it only creates empty files. But definitely better than nothing.

**Comment by Zipdox** [comment]
> Any chance we can merge this in?

I'm afraid my patch only works for video downloading mode. Scraping users doesn't work. Someone more knowledgeable needs to fix it.

**Comment by Liz-chan** [comment]
When I download a user, some videos download without the watermark and some download with the watermark, what would be the reason for that?

**Pull request merged**
