### PR TITLE
Parse new tiktok page format to fix "Error: Can't extract video metadata"

### PR DESCRIPTION
**Pull request by Pterko**
Hello! 
Recently I was struggling with a problem: very often I received an error "Error: Can't extract video metadata".
I've seen that sometimes TikTok returns a page, in which data is stored in a different format. I've added a parser, which will help to receive proper data for that case.

There is no need to merge this PR in this particular implementation, but I hope it will help somebody who struggles with a similar issue.

### CODE REVIEW

**Comment by txj-xyz** [comment]
Same applies to me, and these fixes work for me.

**Comment by vanities** [comment]
This works for me, I will say that their API is now returning different things.

Removals:
authorName
authorId

and timestamp is now a string.

**Comment by txj-xyz** [comment]
I've tested this 100 times on `getVideoMeta()` and 99/100 of the results returned.

Please merge this if possible after edits

**Comment by vanities** [comment]
> You cannot use this PR unless you build and upload your own version to NPM

you can use this in your `package.json`
```
"tiktok-scraper": "https://github.com/Pterko/tiktok-scraper.git",
```

**Comment by txj-xyz** [comment]
@vanities LGTM

**Comment by akaoppa** [comment]
Please merge it

**Comment by akaoppa** [comment]
> I've tested this 100 times on `getVideoMeta()` and 99/100 of the results returned.
> 
> Please merge this if possible after build.

still working for you ?

**Comment by txj-xyz** [comment]
> > I've tested this 100 times on `getVideoMeta()` and 99/100 of the results returned.
> > Please merge this if possible after build.
> 
> still working for you ? It's pretty buggy for me right now

This doesn't help diagnosing, currently this PR implementation is running on a Discord Bot that has about 80k active servers, Pulling about 20-50 `getVideoMeta()` requests a second. It's been working ever since, if you can post the errors that would be helpful so I can make the patch.

**Review by 2M4U — COMMENTED** [review]
Merge

**Comment by bleshik** [comment]
Broken again :(

**Pull request merged**
