### PR TITLE
Add 404 status error handling on getUserProfileInfo

### PR DESCRIPTION
**Pull request by VasylKhoroshcho**
Added 404 status code error handling to have the ability to distinguish blocked request from request for not existing user

### CODE REVIEW

**Comment by asportnoy** [comment]
Could you do the same thing for the other methods too?

**Comment by VasylKhoroshcho** [comment]
@asportnoy Added the same logic to `getVideoMetadata`. In all other cases, we catch an error and return error.message so I think we can leave it as it is to avoid response changes in some methods

**Comment by asportnoy** [comment]
@VasylKhoroshcho A similar thing that would be nice is to have something shown on the `.user` method to segregate failed requests from users with 0 videos, since right now both cases would have the same output. You could do the same thing to other methods that return collectors, eg `.trend`.

**Comment by VasylKhoroshcho** [comment]
@asportnoy `.user` method uses `getUserProfileInfo` in it's flow, so now it possible to segregate failed requests from users with 0 videos. `.trend` and other methods use `submitScrapingRequest` which returns `error.message` in case of an error, so it is also posibble to distinguish requests

**Review by asportnoy — APPROVED** [review]
At some point it would be good to make the responses to all the methods consistent but for now this is fine.

**Comment by art2cool** [comment]
What about merging this pull request?

**Comment by asportnoy** [comment]
@drawrowfly could you take a look at this?

**Comment by suleymanay** [comment]
Ben seni

**Comment by suleymanay** [comment]
www.tiktok.com/@suleyman_ay5

**Review by suleymanay — COMMENTED** [review]
www.tiktok.com/@suleyman_ay5

**Pull request merged**
