### PR TITLE
Add singleMusicMeta method

### PR DESCRIPTION
**Pull request by weavewillG**
Added the ability to get music metadata without getting video feeds. This also solves https://github.com/drawrowfly/tiktok-scraper/issues/167

Tested through `examples/getSingleMusicMeta.ts `

### CODE REVIEW

**Comment by weavewillG** [comment]
The test failure seems to be unrelated to my code change. @drawrowfly please take a look. Thank you.

**Comment by weavewillG** [comment]
@drawrowfly hey Andrew, did you get a chance to review my PR? Hope to get this merged soon so I can start to use it. Thanks!

**Comment by drawrowfly** [comment]
i will review it within 24 hours from now. Thanks )

**Comment by drawrowfly** [comment]
Good job!

**Pull request merged**
