### PR TITLE
Feat/2020 06 16/add luminati proxy

### PR DESCRIPTION
**Pull request by gioggi**
If there are somethings wrong I check it

### CODE REVIEW

**Comment by gioggi** [comment]
#200

**Comment by drawrowfly** [comment]
i will review it within 24 hours from now. Thanks )

**Comment by thibaultleouay** [comment]
Just my two cents but luminati proxies already work with the library at the moment 

If the library have a lot of specific external service provider it will become bloated 

To keep it as simple and efficient it should not include any specific external service

And if you need to use proxies there's an option to specify a proxy

**Comment by drawrowfly** [comment]
@thibaultleouay Can't disagree

You can simply add this proxy via --proxy param 

@gioggi good job though

**Comment by gioggi** [comment]
Thx

**Pull request closed without merging**
